function [ output_args ] = showVersion( input_args )
    
    msgbox({'Developed by: Jose Raul Ruiz Sarmiento (c)2009-2017', ...
    ' ', ...
    'mVision 1.2.0 ' ...
    'Department of System Engineering and Automation', ...
    ' ', 'University of Malaga'},' mVision toolbox ');